resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:279535d1118604037058e1d31dc79c94bfa6a5bce57c24862edad0fa0fd1c579
  name: controller
  newName: registry.connect.redhat.com/streamnative/function-mesh
