{{- if .Values.controllerManager.grpcurlPersistentVolumeClaim }}
apiVersion: batch/v1
kind: Job
metadata:
  name: grpcurl-install
spec:
  template:
    spec:
      containers:
        - name: grpcurl
          image: alpine
          command: [ "/bin/sh" ]
          args:
            - "-c"
            - >-
              wget https://raw.githubusercontent.com/apache/pulsar/master/pulsar-functions/proto/src/main/proto/InstanceCommunication.proto -O /grpcurl/InstanceCommunication.proto &&
              wget https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz -O /grpcurl/grpcurl.tar.gz &&
              cd /grpcurl &&
              tar avxf grpcurl.tar.gz
          volumeMounts:
            - mountPath: /grpcurl
              name: grpcurl-volume
      volumes:
        - name: grpcurl-volume
          persistentVolumeClaim:
            claimName: {{ .Values.controllerManager.grpcurlPersistentVolumeClaim }}
      restartPolicy: Never
{{- end }}