# permissions for end users to edit functionmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshconfig-editor-role
rules:
  - apiGroups:
      - compute.functionmesh.io
    resources:
      - meshconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - compute.functionmesh.io
    resources:
      - meshconfigs/status
    verbs:
      - get
